/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Cascadia Code"', 'Consolas', 'monospace'],
      },
      colors: {
        terminal: {
          bg: '#fafafa',
          surface: '#ffffff',
          border: '#d4d4d4',
          text: '#1e1e1e',
          muted: '#6b7280',
          accent: '#0969da',
          green: '#1a7f37',
          red: '#cf222e',
          yellow: '#9a6700',
        },
        /* Theme-aware colors backed by CSS variables */
        th: {
          page: 'var(--tw-bg-page)',
          card: 'var(--tw-bg-card)',
          input: 'var(--tw-bg-input)',
          hover: 'var(--tw-bg-hover)',
          skeleton: 'var(--tw-bg-skeleton)',
          'skeleton-light': 'var(--tw-bg-skeleton-light)',
        },
        heading: 'var(--tw-text-heading)',
        body: 'var(--tw-text-body)',
        label: 'var(--tw-text-label)',
        muted: 'var(--tw-text-muted)',
        placeholder: 'var(--tw-text-placeholder)',
        disabled: 'var(--tw-text-disabled)',
        'bd': {
          DEFAULT: 'var(--tw-border-default)',
          muted: 'var(--tw-border-muted)',
          strong: 'var(--tw-border-strong)',
          input: 'var(--tw-border-input)',
          dark: 'var(--tw-border-dark)',
          subtle: 'var(--tw-border-subtle)',
        },
        'status-blue': {
          bg: 'var(--tw-blue-bg)',
          'bg-strong': 'var(--tw-blue-bg-strong)',
          DEFAULT: 'var(--tw-blue-text)',
          muted: 'var(--tw-blue-text-muted)',
          dark: 'var(--tw-blue-text-dark)',
          darker: 'var(--tw-blue-text-darker)',
          solid: 'var(--tw-blue-solid)',
          'solid-hover': 'var(--tw-blue-solid-hover)',
          'solid-muted': 'var(--tw-blue-solid-muted)',
        },
        'status-green': {
          bg: 'var(--tw-green-bg)',
          'bg-strong': 'var(--tw-green-bg-strong)',
          DEFAULT: 'var(--tw-green-text)',
          dark: 'var(--tw-green-text-dark)',
          darker: 'var(--tw-green-text-darker)',
          solid: 'var(--tw-green-solid)',
          'solid-dark': 'var(--tw-green-solid-dark)',
          'solid-darker': 'var(--tw-green-solid-darker)',
          'solid-muted': 'var(--tw-green-solid-muted)',
        },
        'status-red': {
          bg: 'var(--tw-red-bg)',
          'bg-strong': 'var(--tw-red-bg-strong)',
          DEFAULT: 'var(--tw-red-text)',
          dark: 'var(--tw-red-text-dark)',
          darker: 'var(--tw-red-text-darker)',
          darkest: 'var(--tw-red-text-darkest)',
          muted: 'var(--tw-red-text-muted)',
          solid: 'var(--tw-red-solid)',
          'solid-dark': 'var(--tw-red-solid-dark)',
          'solid-muted': 'var(--tw-red-solid-muted)',
        },
        sl: {
          50: 'var(--tw-slate-50)',
          100: 'var(--tw-slate-100)',
          200: 'var(--tw-slate-200)',
          300: 'var(--tw-slate-300)',
          400: 'var(--tw-slate-400)',
          500: 'var(--tw-slate-500)',
          600: 'var(--tw-slate-600)',
          700: 'var(--tw-slate-700)',
          800: 'var(--tw-slate-800)',
          900: 'var(--tw-slate-900)',
          950: 'var(--tw-slate-950)',
        },
      },
    },
  },
  plugins: [],
}