declare const ROUTER: {
  HOME: string
  LOGIN: string
  REGISTER: string
  VERIFY_OTP: string
  FORGOT_PASSWORD: string
  RESET_PASSWORD: string
  CLASSES: string
  PLANS: string
  PLANS_RESULT: string
  ABOUT: string
  STUDENT_DASHBOARD: string
  STUDENT_OVERVIEW: string
  MY_PLANS: string
  GOALS: string
  PROFILE: string
  CHANGE_PASSWORD: string
  MY_RESOURCES: string
  NOTIFICATIONS: string
  ADMIN_DASHBOARD: string
  MENTOR_DASHBOARD: string
  MENTOR_AI_PLANS: string
  MENTOR_AI_PLAN_DETAIL: string
  MENTOR_DRAFTS: string
  MENTOR_DRAFT_CREATE: string
  MENTOR_DRAFT_DETAIL: string
  ADMIN_API_KEY: string
  ADMIN_SHOP: string
  ADMIN_SUBSCRIPTION_PLANS: string
  ADMIN_BILLING_TRANSACTIONS: string
  ADMIN_AI_SPENDING: string
  ADMIN_MENTOR_AI_USAGE: string
  ADMIN_USERS: string
  ADMIN_REPORTS: string
  ADMIN_AUDIT_LOGS: string
  MENTOR_PROFILE: string
  QUIZ: string
  TASK: string
  FOCUS_SESSION: string
  FOCUS_SESSION_HISTORY: string
  TASK_REVIEW_DETAIL: string
  CHAT: string
  CHAT_SHARE_PREVIEW: string
  MENTOR_CHAT: string
  CHANNEL_CHAT: string
  MENTOR_CHANNEL_CHAT: string
  SHOP: string
  SUBSCRIPTION: string
  SUBSCRIPTION_CURRENT: string
  BILLING_RESULT: string
  BILLING_HISTORY: string
  SUBSCRIPTION_SUCCESS: string
}

export default ROUTER
